conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("schedule/", include('staff_schedule.urls', namespace='schedule')),
    path('', include('user_configuration.urls', namespace='user_configuration')),
    path("my-tasks/", include('tasks.urls', namespace='my-tasks')),
    path('front-desk/', include('frontdesk.urls', namespace='front-desk')),
    path('executive/', include('executive.urls', namespace='executive')),
    path("payments/", include('payments.urls', namespace="payments")),
    path("trainer/", include('trainer.urls', namespace="trainer")),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, doument_root=settings.MEDIA_ROOT)

frontdesk/urls.py
from django.urls import path

from frontdesk import views

app_name = "frontdesk"

urlpatterns = [
    path("log-classes/", views.log_class_attendance, name="log-classes"),
    path("create-payslip/", views.create_payslip, name="create-payslip"),
]

frontdesk/models.py
from django.db import models

# Create your models here.

frontdesk/views.py
from decimal import Decimal

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import user_passes_test, login_required
from django.db import transaction
from django.shortcuts import render

# Create your views here.
from django.utils import timezone

from conf import constants
from conf.url_tests import not_a_trainer_test, frontdesk_test
from payments.models import PaySlip, GroupClassPayment
from staff_schedule.models import ClockIn


@login_required()
@user_passes_test(frontdesk_test)
def log_class_attendance(request):
    # todo: auto task item
    unregistered_classes = GroupClassPayment.objects.filter(attendees=0, class_paid_for=False,
                                                            attendance_logged=False). \
        prefetch_related("payment_for_class", "payment_for_class__trainer"). \
        order_by("payment_request_created")
    if request.method == "POST":
        if request.POST.get("attendance-for"):
            group_class_payment_id = request.POST.get("attendance-for")
            group_class_payment = GroupClassPayment.objects.get(
                id=int(group_class_payment_id)
            )
            group_class_payment.attendees = request.POST.get(f"class-{group_class_payment_id}")
            group_class_payment.total_payment = group_class_payment.payment_for_class.trainer.payment_per_class
            group_class_payment.attendance_logged = True
            group_class_payment.save()
            return render(request, "partials/post-log-class-attendance.html",
                          {"unregistered_class": group_class_payment}
                          )
        else:
            messages.error(request,
                           "The attendance for this class could not be logged. Please refresh this page and try again.")

    context = {
        'unregistered_classes': unregistered_classes
    }
    return render(request, 'log-class-attendance.html', context)


@user_passes_test(frontdesk_test)
def create_payslip(request):
    # todo: make periodic task
    # step 1: filter for all unpaid classes:
    # step 2: filter for all unpaid classes where the invoice was created on or before the request
    # was made on or before the last saturday of the month
    # todo: add here that only staff that only active staff [staff that are currently working, should be paid
    # this will ensure that when they are deleted from the system and the payslip for their clock ins is once
    # again set to null they are not looked at by the system
    staff_to_create_payslips_for = constants.STAFF_MODEL.objects.filter(
        groups__name__in=["Trainer", "Front Desk"]
    )
    print(staff_to_create_payslips_for)
    current_day = timezone.now()
    with transaction.atomic():
        # # todo: change to objects.create after testing
        # payslip_added_to = PaySlip

        for staff in staff_to_create_payslips_for:
            print(f"for: {staff}")
            payslip_added_to = PaySlip.objects.create()
            unpaid_clock_ins_for_month = ClockIn.objects.filter(
                paid=False,
                time_clocked_in__lte=current_day,
                on_shift=True,
                shift__staff_on_shift=staff,
                payslip=None
            )
            total_deductions = float(0.00)
            total_clock_ins_payment = float(0.00)
            for clock_in in unpaid_clock_ins_for_month:
                clock_in.payslip = payslip_added_to
                total_clock_ins_payment += float(clock_in.payment_for_shift)
                if clock_in.deduction > 0:
                    total_deductions += float(clock_in.deduction)
                clock_in.save()
                payslip_added_to.total_clock_in_wage = float(total_clock_ins_payment)
                payslip_added_to.deductions = float(total_deductions)
                payslip_added_to.final_payment = float(total_clock_ins_payment - total_deductions)

            if staff.groups.filter(name="Trainer").exists():
                unpaid_group_classes_for_month = GroupClassPayment.objects.filter(
                    attendees__gte=1,
                    class_paid_for=False,
                    sent_for_payment=True,
                    payment_request_created__lte=current_day,
                    payment_for_class__trainer=staff,
                    payslip=None
                )
                class_payment = float(0.00)
                for group_class in unpaid_group_classes_for_month:
                    group_class.payslip = payslip_added_to
                    class_payment += float(group_class.total_payment)
                    group_class.save()
                payslip_added_to.total_class_payment = class_payment
                payslip_added_to.final_payment += float(class_payment)
                # todo: add for home and add for classes
            # delete model instance if there was nothing to add to it:
            if payslip_added_to.final_payment == 0:
                payslip_added_to.delete()
            else:
                payslip_added_to.payslip_type = "GNL"
                payslip_added_to.staff = staff
                payslip_added_to.save()

    return render(request, "create-payslip.html")

frontdesk/templates/create-payslip.html
{% extends 'base.html' %}

frontdesk/templates/log-class-attendance.html
 {% extends 'base.html' %}
 {% load static %}

{% block title %}Log Class Attendance{% endblock %}

 {% block content %}
     <div id="user-content" class="ms-9">
        <main id="class-attendance">
            <section class="px-9 pb-10">
                <header class="d-flex flex-column pe-7 my-10">

                    <div class="d-flex flex-row align-items-center">
                        <h1 class="core-page-heading mb-0">Class Attendance</h1>
                        <span class="material-symbols-outlined md-36 themed-icon ms-2">school</span>
                    </div>
                    <div class="mt-2 core-content-subheading">
                        This page allows you to log all class attendances from recent classes</div>
                </header>

                <section class="mt-10">
                    <div class="d-flex flex-row">
                        <div class="col-2 semi-bold zero-point-eight-seven-five-root subtext-shade">
                            <span class="root-size">T</span>RAINER
                        </div>
                        <div class="col-2 semi-bold zero-point-eight-seven-five-root subtext-shade">
                            <span class="root-size">C</span>LASS NAME
                        </div>
                        <div class="col-3 semi-bold zero-point-eight-seven-five-root subtext-shade">
                            <span class="root-size">R</span>EQUEST <span class="root-size">T</span>IME
                        </div>
                        <div class="col-2 semi-bold zero-point-eight-seven-five-root subtext-shade">
                            <span class="root-size">A</span>TTENDEES <span class="root-size">C</span>OUNT
                        </div>
                    </div>

                    {% for unregistered_class in unregistered_classes %}
                        {# todo: for responsive — check partials/post-log-class-attendance.html to ensure responsivity #}
                        <div class="d-flex flex-row align-items-center sub-page-divider pb-7 mt-7" id="unregistered-class-details-{{ forloop.counter0 }}">
                            <div class="col-2">{{ unregistered_class.payment_for_class.trainer }}</div>
                            <div class="col-2">{{ unregistered_class.payment_for_class.class_name }}</div>
                            <div class="col-3">{{ unregistered_class.payment_request_created | date:"l, jS F, Y" }}</div>
                            <form
                                id="unregistered-class-details-{{ unregistered_class.id }}"
                                class="d-flex flex-row col-5 align-items-center"
                                hx-boost="true"
                                action="{% url 'front-desk:log-classes' %}"
                                method="post"
                                hx-target="#unregistered-class-details-{{ unregistered_class.id }}"
                                hx-select="#unregistered-class-details-{{ unregistered_class.id }}"
                                hx-swap="outerHTML"
                                hx-vals='{"attendance-for": "{{ unregistered_class.id }}"}'
                            >
                                <label for="unregistered-class-{{ unregistered_class.id }}" class="d-none"></label>
                                <input type="number" id="unregistered-class-{{ unregistered_class.id }}"
                                       name="class-{{ unregistered_class.id }}" class="me-auto py-2 ps-3" value="1">
                                <button
                                        id="invoice-addition-{{ unregistered_class.id }}"
                                        type="submit"
                                        class="btn-core-ghost zero-point-eight-seven-five-root py-5 px-7 ms-4">Add to Payslip</button>
                            </form>
                        </div>
                    {% endfor %}
                </section>
            </section>
        </main>
     </div>
 {% endblock %}