conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("schedule/", include('staff_schedule.urls', namespace='schedule')),
    path('', include('user_configuration.urls', namespace='user_configuration')),
    path("my-tasks/", include('tasks.urls', namespace='my-tasks')),
    path('front-desk/', include('frontdesk.urls', namespace='front-desk')),
    path('executive/', include('executive.urls', namespace='executive')),
    path("payments/", include('payments.urls', namespace="payments")),
    path("trainer/", include('trainer.urls', namespace="trainer")),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, doument_root=settings.MEDIA_ROOT)

staff_schedule/urls.py
from django.urls import path

from staff_schedule import views

app_name = "schedule"

urlpatterns = [
    path("", views.personal_schedule, name="personal-schedule"),
    path("my-calendar/", views.my_calendar, name="my-calendar"),
    path("clock-in/", views.clock_in, name="clock-in"),
    path("log-clock-in/<clock_in_id>/", views.log_clock_in, name="log-clock-in"),
    path('month-clock-ins/<month_query>/<year_query>/',
         views.clock_ins_for_current_month, name='month-clock-ins'),
    path("clock-in-insights/<clock_in_id>/", views.clock_in_insights, name="clock-in-insights"),
    path("dispute-clock-ins/", views.dispute_clock_in, name="dispute-clock-ins"),
    path("log-dispute/<clock_in_id>", views.log_dispute, name="log-dispute"),
    path("all-clock-ins", views.total_clock_ins, name="total-clock-ins"),
    path("class-details/<class_name>/<int:class_identification>/<slug:slug>/", views.class_details, name="class-details")
    # path('<schedule_weekday>/', views.personal_schedule, name="personal-schedule"),
    # path('<schedule_weekday>/<activity>', views.personal_schedule, name="personal-schedule"),

]

trainer/urls.py
from django.urls import path

from trainer import views

app_name = "trainer"

urlpatterns = [
    path("my-clients/", views.my_clients, name="my-clients"),
    path("my-sessions/<int:calendar_event_identification>/<slug_details>/", views.my_sessions, name="my-sessions"),
    path("add-exercise/<int:calendar_event_identification>/<slug_details>/", views.add_exercise, name="add-exercise"),
]

trainer/models.py
from django.core.exceptions import ValidationError
from django.db import models
from conf import settings


class Client(models.Model):
    first_name = models.CharField(max_length=10, blank=False)
    last_name = models.CharField(max_length=10, blank=False)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class ClientTrainerRelationship(models.Model):
    STATUS_CHOICES = [
        ("ACT", "Active"),
        ("IA", "Inactive")
    ]
    RELATIONSHIP_CHOICES = [
        ("GLD", "Gold"),
        ("SLV", "Silver"),
        ("BRZ", "Bronze")
    ]
    date_joined = models.DateTimeField(auto_now_add=True)
    total_paid = models.DecimalField(decimal_places=2, max_digits=10, blank=False, null=False, default=0.00)
    status = models.CharField(choices=STATUS_CHOICES, max_length=3, blank=False, default="ACT")
    relationship_level = models.CharField(choices=RELATIONSHIP_CHOICES, max_length=3, blank=False, null=False,
                                          default="BRZ")
    trainer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                limit_choices_to={
                                    "groups__name": "Trainer"
                                }, blank=True, null=True)
    client = models.OneToOneField(Client, on_delete=models.SET_NULL, null=True, blank=True)


class TrainerSession(models.Model):
    TRAINING_TYPE = [
        ("GRP", "Group Personal Training"),
        ("SOLO", "Solo Personal Training")
    ]
    session_type = models.CharField(choices=TRAINING_TYPE, max_length=4, blank=False, null=False)
    trainer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                limit_choices_to={
                                    "groups__name": "Trainer"
                                })
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    sessions_left = models.PositiveIntegerField(default=8)


    def __str__(self):
        return f"PT session with {self.trainer} and {self.client}"

    def clean(self):
        try:
            relationship = ClientTrainerRelationship.objects.get(trainer=self.trainer, client=self.client)
        except ClientTrainerRelationship.DoesNotExist:
            raise ValidationError("There is no existing relationship between this client and this trainer. "
                                  "So, you cannot create a session between them.")


class SessionExerciseItem(models.Model):
    exercise_name = models.CharField(max_length=128, blank=True, null=True)
    sets = models.PositiveIntegerField(blank=False, null=False)
    reps = models.PositiveIntegerField(blank=False, null=False)


class SessionExercises(models.Model):
    exercises = models.ManyToManyField(SessionExerciseItem, blank=True)


class GroupClass(models.Model):
    class_name = models.CharField(max_length=100, blank=False)
    description = models.TextField(max_length=1000, blank=True)
    trainer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                limit_choices_to={
                                    "groups__name": "Trainer"
                                })

    def __str__(self):
        return self.class_name

trainer/views.py
from datetime import timedelta

from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db import transaction
from django.shortcuts import render, redirect
from django.utils import timezone

from conf.helper_functions import paginator_helper
from conf.url_tests import trainer_test
from staff_schedule.forms import AddExerciseForm
from staff_schedule.models import ISMSScheduleCalendarEvent, TrainingSessionInfo
from trainer.models import ClientTrainerRelationship, Client, SessionExercises, TrainerSession


@login_required()
@user_passes_test(trainer_test)
def my_clients(request):
    client_list = ClientTrainerRelationship.objects.filter(
        trainer=request.user,
    ).prefetch_related("client")
    page_object = paginator_helper(request, client_list, 9)
    context = {
        "page_object": page_object
    }
    return render(request, "my-clients.html", context)


@login_required()
@user_passes_test(trainer_test)
def my_sessions(request, calendar_event_identification, slug_details):
    context = {}
    current_page_url = request.get_full_path().split("/")
    current_page_id, current_page_slug = current_page_url[3], current_page_url[4]
    calendar_event = ISMSScheduleCalendarEvent.objects.get(
        id=int(calendar_event_identification)
    )
    current_time = timezone.now()
    if request.POST and request.POST.get("starting-session-for"):
        starting_session_for_values = request.POST.get("starting-session-for")
        if starting_session_for_values:
            with transaction.atomic():
                selected_identification_numbers = starting_session_for_values.split(", ")
                TrainingSessionInfo.objects.filter(personal_training_event_id__in=selected_identification_numbers). \
                    update(session_started=True, session_start_time=current_time)
                calendar_event.started = True
                calendar_event.save()
    if request.POST and request.POST.get("ending-session-for"):
        ending_session_for_value = request.POST.get("ending-session-for")
        if ending_session_for_value:
            training_session = TrainingSessionInfo.objects.get(
                id=int(ending_session_for_value)
            )
            training_session.session_end_time = current_time
            training_session.save()

    attached_sessions = TrainingSessionInfo.objects.filter(
        calendar_event_id=int(calendar_event_identification),
        personal_training_event__trainer=request.user
    ).prefetch_related("personal_training_event", "personal_training_event__client")

    sessions_not_started = []
    for session in attached_sessions:
        if not session.session_started:
            sessions_not_started.append(session.id)
    # attached_sessions_ids = [session.id for session in started_sessions_exclude]
    ids_as_string = ", ".join(str(id_number) for id_number in sessions_not_started)

    if attached_sessions:
        if calendar_event.start_date.date() == current_time.date() and current_time >= (
                calendar_event.start_date - timedelta(minutes=30)):
            # trainer can start the session if they have not already started it in the past:
            context['can_start_session'] = False if calendar_event.started else True
        else:
            context['can_start_session'] = False

    context["add_exercises_form"] = AddExerciseForm()
    context['attached_sessions'] = attached_sessions
    context['attached_sessions_ids'] = ids_as_string
    context['current_id'] = int(current_page_id)
    context['current_slug'] = current_page_slug
    context["calendar_event"] = calendar_event
    return render(request, "my-sessions.html", context)


def add_exercise(request, calendar_event_identification, slug_details):
    if request.POST:
        # todo: think about model form here
        form = AddExerciseForm(request.POST)
        if form.is_valid():
            # print(request.POST.get("choose-users"))
            users_editing = request.POST.get("choose-users")
            with transaction.atomic():
                new_training_exercise = form.save()
                if users_editing != "all":
                    session_to_update = TrainingSessionInfo.objects.get(
                        calendar_event_id=int(calendar_event_identification),
                        personal_training_event_id=int(users_editing)
                    )
                    session_to_update.exercises_performed.add(new_training_exercise)
                    session_to_update.save()
                else:
                    sessions_to_update = TrainingSessionInfo.objects.filter(
                        calendar_event_id=int(calendar_event_identification)
                    )
                    for session in sessions_to_update:
                        session.exercises_performed.add(new_training_exercise)
                        session.save()
            return redirect("trainer:my-sessions",
                            calendar_event_identification=calendar_event_identification,
                            slug_details=slug_details)

trainer/templates/my-clients.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}
    My Clients
{% endblock %}

{% block content %}
    <div id="user-content" class="mb-10">
        <main id="my-clients">
            <header id="header-content" class="mt-10 pb-7 px-9">
                <div class="d-flex flex-row align-items-center">
                    <h1 class="core-page-heading mb-0">My Clients</h1>
                    <span class="material-symbols-outlined md-36 themed-icon ms-2">group</span>
                </div>
                <div class="mt-2 core-content-subheading">
                    Your clients page details all the clients that you have ever had as an iSweat Trainer.
                    Click on the more button to view all the sessions that you have ever had with them.
                </div>
                <div class="mt-9">
                    <div class="input-group">
                        <div class="custom-form-icon ps-7">
                            <span class="material-symbols-outlined md-48 ms-2 py-6 md-grey">search</span>
                        </div>
                        <input type="text" class="py-6 form-control custom-form me-9" aria-label="search" aria-describedby="search-for-clients"
                               placeholder="Start typing a name to filter through your clients ...">
                    </div>
                </div>
            </header>

            <section class="px-9">
                <div class="d-flex flex-row flex-wrap justify-content-between">
                    {% for client in page_object %}
                        <div class="d-flex flex-column transparent-board col-3 pt-11 pb-10 ps-7 me-9 mt-7">
                            {% if client.status == "ACT"%}
                                <div class="success-text d-flex flex-row align-items-center">
                                    <span class="material-symbols-outlined md-36 md-green pe-2">check_circle</span>
                                    <div class="semi-bold zero-point-eight-seven-five-root">Active {{ client.get_relationship_level_display }} Client</div>
                                </div>
                            {% else %}
                                <div class="failure-text d-flex flex-row align-items-center">
                                    <span class="material-symbols-outlined md-36 md-red pe-2">cancel</span>
                                    <div class="semi-bold zero-point-eight-seven-five-root">Inactive {{ client.get_relationship_level_display }} Client</div>
                                </div>
                            {% endif %}
                            <div class="zero-point-eight-seven-five-root subtext-shade light mt-8">Since {{ client.date_joined | date:"d/m/Y" }}</div>
                            <div class="mt-2 light one-point-one-two-five-root">{{ client.client.first_name }} {{ client.client.last_name }}</div>
                            <div class="total-paid-to-trainer pt-6 double-root semi-bold">{{ client.total_paid | intcomma}} NGN</div>
                            <div hx-boost="true" class="mt-8">
                                <a href="">
                                    <span class="material-symbols-outlined md-48 md-blue rotate-90-right">expand_circle_down</span>
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </section>
        </main>
    </div>
{% endblock %}

trainer/templates/my-sessions.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    My Sessions
{% endblock %}

{% block content %}
    <main id="user-content" class="mb-10">
        <div id="session-details">
            <header id="session-details" class="pb-10 px-9">
                <div class="d-flex flex-row pointer pt-10 pb-7 align-items-center"
                     hx-post="{% url 'schedule:my-calendar' %}"
                     hx-select="#user-content"
                     hx-target="#user-content"
                     hx-swap="outerHTML"
                     hx-push-url="true"
                >
                    <span class="material-symbols-outlined md-24 md-grey">arrow_back</span>
                    <span class="subtext-shade regular zero-point-eight-seven-five-root">Back to  My Calendar</span>
                </div>
                <div class="double-root thin">
                    Training With
                    {% for pt_session in training_session.personal_training_event.all %}{% if forloop.counter0 >= 1 %}, {% if forloop.last %}and {% endif %}{% endif %}{{ pt_session.client }}{% endfor %}
                </div>
                <span class="mt-2 core-content-subheading">
                    Control your sessions and log exercises after the session is completed to allow your clients know how they performed.
                </span>

                <section id="session-control" class="d-flex flex-row align-items-end">
                    <div
                        type="button"
                        {% if can_start_session %}
                            class="d-flex flex-column align-items-center opaque-board success-text mt-6 col-4 py-9 pointer"
                            data-bs-toggle="modal"
                            data-bs-target="#beginSessionModal"
                        {% elif calendar_event.started %}
                            class = "d-flex flex-column align-items-center opaque-board failure-text mt-6 col-4 py-9 pointer"
                            data-bs-toggle="modal"
                            data-bs-target="#endSessionModal"
                        {% else %}
                            class="d-flex flex-column align-items-center opaque-board mt-6 col-4 py-9 subtext-shade"
                        {% endif %}
                    >
                        <span class="material-symbols-outlined md-48">play_circle</span>
                        <div class="semi-bold mt-4">
                            {% if can_start_session %}
                                Start Session
                            {% elif calendar_event.started == True and calendar_event.ended == False %}
                                End Session
                            {% else %}
                                Start Session
                            {% endif %}</div>
                        <div class="semi-bold triple-root mt-4">{% now "H:i" %}</div>
                    </div>

                    {% if calendar_event.started %}
                        {% for item in attached_sessions %}
                            {% if item.session_started == False %}
                                <button class="btn-alt-ghost d-flex flex-row align-items-center py-4 px-7 ms-7 zero-point-eight-seven-five-root">
                                    <span class="material-symbols-outlined md-36 md-green me-2">play_circle</span>
                                    Start Session For {{ item.personal_training_event.client.first_name }}
                                </button>
                            {% endif %}
                        {% endfor %}
                {% endif %}

                    <div class="modal modal-lg fade" id="beginSessionModal" tabindex="-1" aria-labelledby="beginSessionModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                              <div class="modal-header semi-bold one-point-one-two-five-root py-7 px-7">
                                <h1 class="modal-title ps-5" id="beginSessionModalLabel">Start Session For</h1>
                                <button type="button" class="btn-close d-flex align-items-center justify-content-center" data-bs-dismiss="modal" aria-label="Close">
                                    <span class="material-symbols-outlined md-24 md-white">close</span>
                                </button>
                              </div>
                              <div class="modal-body py-7 px-7">
                                    <div class="subtext-shade zero-point-eight-seven-five-root medium">
                                        It is essential that you accurately time your sessions.
                                        You can start a session for each individual member of the group, or begin it for the entire group if they are all present.
                                    </div>
                                  <div class="d-flex flex-row flex-wrap mt-7">
                                      {% for item in attached_sessions %}
                                        {% if item.session_started == False %}
                                            <button
                                                    type="button"
                                                    data-selected-user-id = "{{ item.id }}"
                                                    class="session-control d-flex flex-column failure-mini-board py-6 px-6 col {% if not forloop.last %}me-7{% endif %}">
                                            <span class="material-symbols-outlined md-red md-36">close</span>
                                            <span class="mt-5 light subtext-shade">Start Session For</span>
                                            <span class="mt-7 failure-text double-root medium">{{ item.personal_training_event.client.first_name }}</span>
                                            </button>
                                        {% endif %}
                                      {% endfor %}
                                  </div>
                              </div>
                              <div class="modal-footer px-7 pb-10" id="start-session">
                                <button type="button" class="btn-alt-ghost d-flex flex-row align-items-center py-4 px-7"
                                        id="start-session-for-all-btn"
                                        data-bs-dismiss="modal"
                                        hx-post="{% url 'trainer:my-sessions' current_id current_slug %}"
                                        hx-vals='{"starting-session-for": "{{ attached_sessions_ids }}"}'
                                        hx-select="#user-content"
                                        hx-target="#user-content"
                                        hx-swap="outerHTML"
                                >
                                    <span class="material-symbols-outlined md-green md-36">group</span>
                                    Start Session For All
                                </button>
                              </div>
                            </div>
                          </div>
                    </div>


                    <div class="modal modal-lg fade" id="endSessionModal" tabindex="-1" aria-labelledby="endSessionModalLabel" aria-hidden="True">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                                <div class="modal-header semi-bold one-point-one-two-five-root py-7 px-7">
                                    <h1 class="modal-title ps-5" id="endSessionModalLabel">End Session For</h1>
                                    <button type="button" class="btn-close d-flex align-items-center justify-content-center" data-bs-dismiss="modal" aria-labelledby="Close">
                                        <span class="material-symbols-outlined md-24 md-white">close</span>
                                    </button>
                                </div>
                                <div class="modal-body py-7 px-7">
                                    <div class="subtext-shade zero-point-eight-seven-five-root medium">
                                        It is essential that you accurately time your sessions.
                                        You can end a session for each individual member of the group, or end it for the entire group if they are all present.
                                    </div>
                                    <div class="d-flex flex-row flex-wrap mt-7">
                                        {% for item in attached_sessions %}
                                            {% if item.session_started == True and item.session_end_time == None %}
                                                <button
                                                    type="button"
                                                    data-selected-user-id="{{ item.id }}"
                                                    class="end-session-control d-flex flex-column failure-mini-board py-6 px-6 col {% if not forloop.last %}me-7{% endif %}">
                                                <span class="material-symbols-outlined md-red md-36">close</span>
                                                <span class="mt-5 light subtext-shade">End Session For</span>
                                                <span class="mt-7 failure-text double-root medium">{{ item.personal_training_event.client.first_name }}</span>
                                                </button>
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                </div>
                                <div class="modal-footer px-7 pb-10" id="end-session">
                                    <button type="button" class="btn-alt-ghost d-flex flex-row align-items-center py-4 px-7"
                                            disabled
                                            id="end-session-for-all-btn"
                                            data-bs-dismiss="modal"
                                            hx-post="{% url "trainer:my-sessions" current_id current_slug %}"
                                            hx-vals='{"ending-session-for": "{{ attached_sessions_ids }}"}'
                                            hx-select="#user-content"
                                            hx-target="#user-content"
                                            hx-swap="outerHTML">
                                        <span class="material-symbols-outlined md-green md-36">group</span>
                                        End Session for Selected
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </header>

            <section class="px-9">
                <div class="d-flex flex-row align-items-center justify-content-between">
                    <h2 class="thin one-point-five-root-root">Exercise List</h2>
                </div>

                <section class="d-flex flex-column align-items-center sub-page-divider pb-10" id="user-table">
                    <table class="table mt-9">
                        <thead class="subpage-table">
                            <tr>
                                <th scope="col" class="py-4 ps-10">Name</th>
                                <th scope="col" class="py-4 pe-14">Performed By</th>
                                <th scope="col" class="py-4">Sets</th>
                                <th scope="col" class="py-4">Reps</th>
                                <th scope="col" class="py-4"></th>
                            </tr>
                        </thead>

                        <tbody>
                        </tbody>
                    </table>
                </section>

                <section class="d-flex flex-column mt-10" id="add-exercises">
                    <form
                            id="add-exercises-form"
                            hx-post="{% url 'trainer:add-exercise' current_id current_slug %}"
                            hx-swap="none"
                    >
                        <div class="d-flex flex-column">
                            <label for="choose-users" class="extra-light zero-point-eight-seven-five-root mb-4">Performed By</label>
                            <select id="choose-users" name="choose-users" class="form-select py-4 px-7 w-50">
                                {% for item in attached_sessions %}
                                    <option value="{{ item.id }}">{{ item.personal_training_event.client.first_name }}</option>
                                {% endfor %}
                                <option value="all">All Clients</option>
                            </select>
                        </div>
                        {% for field in add_exercises_form %}
                            <div class="d-flex flex-column mt-6">
                                <label for="{{ field.id_for_label }}" class="extra-light zero-point-eight-seven-five-root mb-4">{{ field.label }}</label>
                                <div>{{ field }}</div>
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn-core-ghost px-7 py-4  mt-7">Add Exercise</button>
                    </form>
                </section>
            </section>
        </div>

    <script type="module" src="{% static 'js/calendar_details/modalControl.js' %}" defer></script>
    </main>
{% endblock %}