conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("schedule/", include('staff_schedule.urls', namespace='schedule')),
    path('', include('user_configuration.urls', namespace='user_configuration')),
    path("my-tasks/", include('tasks.urls', namespace='my-tasks')),
    path('front-desk/', include('frontdesk.urls', namespace='front-desk')),
    path('executive/', include('executive.urls', namespace='executive')),
    path("payments/", include('payments.urls', namespace="payments")),
    path("trainer/", include('trainer.urls', namespace="trainer")),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, doument_root=settings.MEDIA_ROOT)

staff_schedule/urls.py
from django.urls import path

from staff_schedule import views

app_name = "schedule"

urlpatterns = [
    path("", views.personal_schedule, name="personal-schedule"),
    path("my-calendar/", views.my_calendar, name="my-calendar"),
    path("clock-in/", views.clock_in, name="clock-in"),
    path("log-clock-in/<clock_in_id>/", views.log_clock_in, name="log-clock-in"),
    path('month-clock-ins/<month_query>/<year_query>/',
         views.clock_ins_for_current_month, name='month-clock-ins'),
    path("clock-in-insights/<clock_in_id>/", views.clock_in_insights, name="clock-in-insights"),
    path("dispute-clock-ins/", views.dispute_clock_in, name="dispute-clock-ins"),
    path("log-dispute/<clock_in_id>", views.log_dispute, name="log-dispute"),
    path("all-clock-ins", views.total_clock_ins, name="total-clock-ins"),
    path("class-details/<class_name>/<int:class_identification>/<slug:slug>/", views.class_details, name="class-details")
    # path('<schedule_weekday>/', views.personal_schedule, name="personal-schedule"),
    # path('<schedule_weekday>/<activity>', views.personal_schedule, name="personal-schedule"),

]

trainer/urls.py
from django.urls import path

from trainer import views

app_name = "trainer"

urlpatterns = [
    path("my-clients/", views.my_clients, name="my-clients"),
    path("my-sessions/<int:calendar_event_identification>/<slug_details>/", views.my_sessions, name="my-sessions"),
    path("add-exercise/<int:calendar_event_identification>/<slug_details>/", views.add_exercise, name="add-exercise"),
]

staff_schedule/models.py
import json
from datetime import timedelta
from decimal import Decimal

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models, IntegrityError
from django.db.models import Q
from django.utils import timezone
from django_celery_beat.models import CrontabSchedule, PeriodicTask

from payments.models import PaySlip
from trainer.models import Client, TrainerSession, GroupClass, SessionExerciseItem


class Weekday(models.Model):
    WEEKDAYS = [
        ("0", "Monday"),
        ("1", "Tuesday"),
        ("2", "Wednesday"),
        ("3", "Thursday"),
        ("4", "Friday"),
        ("5", "Saturday"),
        ("6", "Sunday")
    ]
    day = models.CharField(max_length=1, choices=WEEKDAYS)

    def __str__(self):
        return self.get_day_display()


class Meeting(models.Model):
    meeting_title = models.CharField(max_length=100, blank=False)
    description = models.TextField(max_length=3000, blank=False)
    staff_attending = models.ManyToManyField(settings.AUTH_USER_MODEL)

    def __str__(self):
        return self.meeting_title


class ISMSScheduleFixedEvent(models.Model):
    RECURRING_CHOICES = [
        ("DLY", "Daily"),
        ("WKLY", "Weekly"),
        ("MTH", "Monthly")
    ]
    EVENT_TYPES = [
        ("CS", "Class"),
        ("MT", "Meeting"),
    ]
    WEEKDAYS = [
        ("0", "Monday"),
        ("1", "Tuesday"),
        ("2", "Wednesday"),
        ("3", "Thursday"),
        ("4", "Friday"),
        ("5", "Saturday"),
        ("6", "Sunday")
    ]
    LOCATIONS = [
        ("OF", "Office"),
        ("MTA", "Multi-Tasking Area"),
        ("SA", "Strength Area"),
        ("ISMS", "ISMS Platform"),
        ("CA", "Class Area")
    ]
    schedule_type = models.CharField(choices=EVENT_TYPES, max_length=2)
    schedule_day = models.CharField(choices=WEEKDAYS, max_length=1, blank=True)
    group_class = models.ForeignKey(GroupClass, on_delete=models.CASCADE, null=True, blank=True)
    staff_meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE, null=True, blank=True)
    location = models.CharField(choices=LOCATIONS, max_length=4)
    slug = models.SlugField(max_length=20, blank=True, null=True, unique=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    # # todo: implementing this functionality
    # recurring = models.BooleanField(default=False)
    # recurring_interval = models.CharField(
    #     choices=RECURRING_CHOICES, max_length=4
    # )
    # recurring_count = models.PositiveIntegerField(default=0, blank=True, null=True)

    def __str__(self):
        if self.group_class:
            return str(self.group_class)
        elif self.staff_meeting:
            return str(self.staff_meeting)
        else:
            return super().__str__()

    def clean(self):
        if self.staff_meeting and self.group_class:
            raise ValidationError("You May Only Select One Type of Event for a Fixed Schedule Item")
        if self.start_time.weekday() != self.end_time.weekday():
            raise ValidationError("ISMS Fixed Events May Only Occur on a Single Date. "
                                  "Please Ensure that Both the Start and End Time are On The Same Date")

    def save(self, *args, **kwargs):
        self.schedule_day = str(self.start_time.weekday())
        if self.pk is None:
            super().save(*args, **kwargs)

        if self.group_class:
            self.schedule_type = "CS"
        elif self.staff_meeting:
            self.schedule_type = "MT"

        self.slug = f"{self.schedule_type}-ID-{self.location}-{self.id}"
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "ISMS Schedule Fixed Event"


# class CalendarEvent(models.Model):
#     start_time = models.DateTimeField()
#     end_time = models.DateTimeField()


class ISMSScheduleCalendarEvent(models.Model):
    CALENDAR_EVENT_SCHEDULE_TYPES = [
        ("MT", "Meeting"),
        ("SPE", "Special Event"),
        ("PT", "Personal Training"),
        ("CS", "Class")
    ]
    schedule_type = models.CharField(choices=CALENDAR_EVENT_SCHEDULE_TYPES, max_length=3)
    personal_training_event = models.ManyToManyField(TrainerSession, blank=True, through='TrainingSessionInfo')
    # todo: add class here — this will be used in cases where a trainer is covering for a class.
    meeting_event = models.ForeignKey(Meeting, on_delete=models.CASCADE, null=True, blank=True)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    slug = models.SlugField(max_length=400, blank=True)
    started = models.BooleanField(default=False)
    ended = models.BooleanField(default=False)


    def clean(self):
        # if self.pk:
        #     # todo: move this functionality to view on creation
        #     if self.personal_training_event and self.meeting_event:
        #         raise ValidationError("You May Only Select One Type of Event for a Calendar Event")
        if self.start_date.weekday() != self.end_date.weekday():
            raise ValidationError("ISMS Calendar Events May Only Occur Over the Course of a Single Day")

    def save(self, *args, **kwargs):
        if self.pk is None:
            # each time that a PT sessions is added to the calendar, it must be reduced by one:
            # todo: each time that a PT session is deleted from the calendar, one should be added to it
            super().save(*args, **kwargs)
            # test this:
            # todo: this functionality will have to be moved to the view / form:
            if self.personal_training_event:
                for event in self.personal_training_event.all():
                    try:
                        event.sessions_left -= 1
                        if event.sessions_left == 0:
                            raise ValidationError(f"No More Sessions Can Be Allocated For {event}")
                        event.save()
                    except IntegrityError:
                        raise ValidationError(f"No More Sessions Can Be Allocated For {event}")

        if not self.slug:
            self.slug = f"ISMS-Calendar-Event-{self.id}-{self.schedule_type}"
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "ISMS Schedule Calendar Event"


class TrainingSessionInfo(models.Model):
    personal_training_event = models.ForeignKey(TrainerSession, on_delete=models.CASCADE)
    calendar_event = models.ForeignKey(ISMSScheduleCalendarEvent, on_delete=models.CASCADE)
    session_started = models.BooleanField(default=False)
    session_start_time = models.DateTimeField(null=True, blank=True)
    session_end_time = models.DateTimeField(null=True, blank=True)
    exercises_performed = models.ManyToManyField(SessionExerciseItem)


class Shift(models.Model):
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    staff_on_shift = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    weekday = models.ForeignKey(Weekday, null=True, blank=True, on_delete=models.CASCADE)

    # todo shift covering functionality here test for normalization

    def __str__(self):
        return "{} starting at {} and ending at {}".format(self.staff_on_shift,
                                                           self.start_time.time(),
                                                           self.end_time.time())

    def save(self, *args, **kwargs):
        current_weekday = self.start_time.weekday()
        self.weekday = Weekday.objects.get(day=str(current_weekday))
        if self.pk is None:
            # todo: ensure that any changes to the shift will affect any clock ins posted — generally will be a maximum
            #  of 2 the current one and the one that may have been created automatically with celery. this will prevent
            #  scenarios where multiple clock ins will be created after a shift has been changed
            super().save(*args, **kwargs)
            corresponding_clockin, _ = ClockIn.objects.get_or_create(shift=self, status="CLSD",
                                                                     shift_starts=self.start_time,
                                                                     shift_ends=self.end_time)
            corresponding_clockin.save()
        super().save(*args, **kwargs)


class ClockIn(models.Model):
    """
    :status: indicates the different status that a clock in could have
    :shift: indicates the shift that the clock in is linked to
    :time_clocked_in: indicates the time that the user has clocked in. value will be used to calculate total pay
    :active: indicates whether a clock in is open or closed
    :on_shift: indicates whether a staff is currently on a shift or not
    :paid: indicates the total amount that a staff has been paid for that shift
    :deduction: indicates the total amount that a staff has been deducted if they showed up late for the shift
    """
    # todo: in future migrations, closed should become inactive as this is a better descriptor
    status = [
        ("CLSD", "Closed"),
        ("EA", "Early"),
        ("LTE", "Late"),
        ("DSP", "Disputing"),
        ("DSPF", "Dispute Failed"),
        ("DSPS", "Dispute Succeeded")
    ]
    shift = models.ForeignKey(Shift, on_delete=models.SET_NULL, null=True)
    shift_starts = models.DateTimeField(blank=True, null=True)
    shift_ends = models.DateTimeField(blank=True, null=True)
    time_clocked_in = models.DateTimeField(blank=True, null=True)
    status = models.CharField(choices=status, max_length=4, blank=False, null=False, default="CLSD")
    active = models.BooleanField(default=False)
    on_shift = models.BooleanField(default=False)
    paid = models.BooleanField(default=False)
    payment_for_shift = models.DecimalField(default=0.00, max_digits=12, decimal_places=2, blank=True, null=True)
    deduction = models.DecimalField(default=0.00, max_digits=12, decimal_places=2, blank=True, null=True)

staff_schedule/forms.py
from django import forms
from django.forms import ModelForm, BaseModelFormSet, TextInput, Textarea, ClearableFileInput, NumberInput

from staff_schedule.models import Dispute, DisputeAttachment
from trainer.models import SessionExerciseItem


class DisputeFormSet(BaseModelFormSet):
    class Meta:
        fields = ("dispute_description",)


class DisputeForm(ModelForm):
    class Meta:
        model = Dispute
        fields = ("dispute_description",)

        widgets = {
            "dispute_description": Textarea(
                attrs={"class": "text-form py-6 px-6 extra-light zero-point-eight-seven-five-root w-100"}
            )
        }


class MyClearableFileInput(ClearableFileInput):
    initial_text = 'currently'
    input_text = 'change'
    clear_checkbox_label = 'clear'


class DisputeAttachmentForm(ModelForm):
    class Meta:
        model = DisputeAttachment
        fields = ("document",)

        widgets = {
            "document": ClearableFileInput(
                attrs={
                    "multiple": True,
                    "class": "success-text"
                }
            )
        }


class AddExerciseForm(ModelForm):

    class Meta:
        model = SessionExerciseItem
        fields = ("exercise_name", "sets", "reps")

        widgets = {
            "exercise_name": TextInput(
                attrs={
                    "class": "text-form py-4 px-7 col-6"
                }
            ),
            "sets": NumberInput(
                attrs={
                    "class": "py-4 px-7"
                }
            ),
            "reps": NumberInput(
                attrs={
                    "class": "py-4 px-7"
                }
            ),
        }

        labels = {
            "exercise_name": "Exercise Name"
        }

staff_schedule/templates/clock-ins-this-month.html
{% extends 'base.html' %}
{% load static %}
{% load staffschedule_extras %}

{% block title %}Clock Ins for {{ month_observing }}{% endblock %}

{% block content %}
    <div id="user-content" class="mb-10">
        <div id="clock-ins-this-month">
            <section id="header-content"
                     class="header-content bordered sub-page-divider pb-10 px-9"
            >
                 <div
                        class="d-flex flex-row pointer pt-10 align-items-center"
                        hx-post="{% url 'schedule:clock-in' %}"
                        hx-select="#user-content"
                        hx-target="#user-content"
                        hx-swap="outerHTML"
                        hx-push-url="true"
                        id="back-button"
                >
                    <span class="material-symbols-outlined md-24 md-grey">arrow_back</span>
                    <span class="subtext-shade regular zero-point-eight-seven-five-root">Back to Clock Ins</span>
                </div>

                <h1 class="sub-core-heading mt-7" id="clock-ins-observing-month">Clock Ins For {{ month_observing }} </h1>
                <span class="mt-2 core-content-subheading">View and dispute logged clock ins for current and past months</span>

                <div class="d-flex flex-row mt-10 justify-content-between">
                    <div id="early-clock-ins-heading" class="success-text">
                        <div>Early Clock Ins</div>
                        <div class="quadruple-root medium">{{ early_clock_ins_count }}</div>
                        <div class="subtext-shade zero-point-seven-five-root">From {{ month_observing }} 1, {{ year_observing }} to {{ month_observing }} {{ end_date }}, {{ year_observing }}</div>
                    </div>

                    <div id="late-clock-ins-heading" class="failure-text">
                        <div>Late Clock Ins</div>
                        <div class="quadruple-root medium">{{ late_clock_ins_count }}</div>
                        <div class="subtext-shade zero-point-seven-five-root">From {{ month_observing }} 1, {{ year_observing }} to {{ month_observing }} {{ end_date }}, {{ year_observing }}</div>
                    </div>

                    <div id="all-clock-ins-heading">
                        <div>All Clock Ins</div>
                        <div class="quadruple-root medium">{{ all_clock_ins_count }}</div>
                        <div class="subtext-shade zero-point-seven-five-root">From {{ month_observing }} 1, {{ year_observing }} to {{ month_observing }} {{ end_date }}, {{ year_observing }}</div>
                    </div>
                </div>

                <div class="d-flex mt-8">
                    <button
                            class="material-symbols-outlined md-36 md-blue button icon-flip pointer"
                            hx-post = "{% url 'schedule:month-clock-ins' previous_month_query previous_year_query %}"
                            hx-select="#user-content"
                            hx-target="#user-content"
                            hx-swap="outerHTML"
                            hx-push-url="true"
                    >next_plan</button>
                    <button
                            class="material-symbols-outlined button md-36 md-blue pointer"
                            {{ next_button_disabled }}
                            hx-post = "{% url 'schedule:month-clock-ins' next_month_query next_year_query %}"
                            hx-select="#user-content"
                            hx-target="#user-content"
                            hx-swap="outerHTML"
                            hx-push-url="true"
                    >next_plan</button>
                </div>

            </section>

            <section id="tabular-content" class="px-9 mt-10">
                <div class="d-flex flex-row justify-content-between align-items-center">
                    <div class="thin one-point-five-root">
                        {{ month_observing }} Clock Ins List
                    </div>
                    <div class="d-flex flex-row align-items-center">
                        <button
                                id="clock-in-dispute-button"
                                class="btn-core-ghost medium
                                zero-point-eight-seven-five-root py-5 px-7 me-6"
                                hx-boost="true"
                                hx-get="{% url 'schedule:dispute-clock-ins' %}"
                                hx-select="#user-content"
                                hx-target="#user-content"
                                hx-swap="outerHTML"
                                hx-push-url="true"
                                disabled
                        >Dispute Clock In</button>
                        <button
                                class="btn-alt-ghost medium zero-point-eight-seven-five-root py-5 px-7 d-flex align-items-center"
                        >
                            <span class="material-symbols-outlined md-18 me-2">tune</span>
                            <span>Add Filters</span> </button>
                    </div>
                </div>

                <section id="user-table" class="d-flex flex-column align-items-center">
                    <table class="table mt-9">
                        <thead class="subpage-table">
                            <tr>
                                <th scope="col" class="py-4 ps-10"></th>
                                <th scope="col" class="py-4">ID</th>
                                <th scope="col" class="py-4 pe-14">Date</th>
                                <th scope="col" class="py-4">Start</th>
                                <th scope="col" class="py-4">Clocked</th>
                                <th scope="col" class="py-4">Deduction</th>
                                <th scope="col" class="py-4">Payment</th>
                                <th scope="col" class="py-4">Status</th>
                                <th scope="col" class="py-4"></th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for clock_in in page_object %}
                                <tr class="sub-table-data clock-in-table">
                                    <td class="py-5 ps-10">
                                        <label for="{{ clock_in.id }}"><span class="d-none">Select Clock In {{ clock_in.id }}</span></label>
                                        <input
                                                type="checkbox" class="form-check-input"
                                                id="{{ clock_in.id }}" name="clock-in-{{ clock_in.id }}" value="{{ clock_in.id }}"
                                                {% if clock_in.status != "LTE" %}
                                                    disabled
                                                {% endif %}
                                        />
                                    </td>
                                    <td class="py-5 table-non-core light">CID-{{ clock_in.id }}</td>
                                    <td class="py-5 table-non-core light">{{ clock_in.shift_starts | date:"dS M Y" }}</td>
                                    <td class="py-5 table-core">{{ clock_in.shift_starts | date:"H:i" }}</td>
                                    <td class="py-5 table-core">{{ clock_in.time_clocked_in | date:"H:i" }}</td>
                                    <td class="py-5 table-core">{{ clock_in.deduction }} NGN</td>
                                    <td class="py-5 table-core">{{ clock_in.payment_for_shift | subtract:clock_in.deduction  }} NGN</td>
                                    <td class="py-5 table-core">
                                        <span class="d-none status-identifier">{{ clock_in.status }}</span>
                                        <span class="material-symbols-outlined md-36 me-1 status-icon-indicator"></span>
                                        <span class="status-text"></span>
                                    </td>
                                    <td class="py-5 alternative-blue medium table-core" hx-boost="true" hx-select="#user-content" hx-target="#user-content" hx-swap="outerHTML">
                                        <a href="{% url 'schedule:clock-in-insights' clock_in.id %}">Insights
                                        <span class="material-symbols-outlined md-36 ms-1">arrow_circle_right</span>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% include 'pagination.html' with select_id="#user-table" target_id="#user-table" %}
                </section>
            </section>
            <script src="{% static 'js/clock_ins_view/clockInDisputeSelector.js' %}" defer></script>
            <script src="{% static 'js/clock_ins_view/totalClockInsHandler.js' %}" defer></script>
        </div>
    </div>
{% endblock %}

staff_schedule/templates/personal-schedule.html
{% extends 'base.html' %}
{% load static %}
{% load staffschedule_extras %}

{% block content %}
    <div id="user-content" class="mb-10">
        <main id="staff-schedule">
            <section class="sub-page-divider px-9 pb-10">
                <header class="d-flex flex-column pe-7 my-10">

                    <div class="d-flex flex-row align-items-baseline">
                        <h1 class="core-page-side-heading mb-0">Your Schedule</h1>
                        <span class="material-symbols-outlined md-36 themed-icon ms-2">event_upcoming</span>
                    </div>
                    <div class="mt-2 core-content-subheading">
                        Your schedule provides details of all the activities that you will need to carry out while at the gym.
                        You can also view the full iSweat Fitness rota here.</div>
                </header>

                <section id="activity-selection" class="d-flex flex-row" onload="personalScheduleHandler()">
                    {# todo: roles settings here #}
                    {% with user_group=request.user|has_group:"Trainer" %}
                    <button
                            id="all-activities-button"
                            class="activity-buttons py-4 px-7"
                            hx-get="{% url 'schedule:personal-schedule' %}"
                            hx-vals='{"weekday": "{{ schedule_weekday}}", "activity": "ALL"}'
                            hx-select="#user-activities"
                            hx-target="#user-activities"
                            hx-swap="outerHTML"
                            hx-push-url="true"
                    >All Activities</button>
                    {% if user_group %}
                        <button
                                id="class-list-button"
                                class="activity-buttons py-4 px-7 ms-2"
                                hx-get="{% url 'schedule:personal-schedule' %}"
                                hx-vals='{"weekday": "{{ schedule_weekday}}", "activity": "CS"}'
                                hx-select="#user-activities"
                                hx-target="#user-activities"
                                hx-swap="outerHTML"
                                hx-push-url="true"
                        >Classes</button>
                    {% endif %}
                    <button
                            id="meeting-list-button"
                            class="activity-buttons py-4 px-7 ms-2"
                            hx-get="{% url 'schedule:personal-schedule' %}"
                            hx-vals='{"weekday": "{{ schedule_weekday}}", "activity": "MT"}'
                            hx-select="#user-activities"
                            hx-target="#user-activities"
                            hx-swap="outerHTML"
                            hx-push-url="true"
                    >Meetings</button>
                    {% if user_group %}
                        <button
                                id="personal-training-list-button"
                                class="activity-buttons py-4 px-7 ms-2"
                                hx-get="{% url 'schedule:personal-schedule' %}"
                                hx-vals='{"weekday": "{{ schedule_weekday}}", "activity": "PT"}'
                                hx-select="#user-activities"
                                hx-target="#user-activities"
                                hx-swap="outerHTML"
                                hx-push-url="true"
                        >Personal Training</button>
                    {% endif %}
                    {% endwith %}
                </section>
            </section>

        <section id="user-activities" class="px-9 mt-10">
                <header class="d-flex flex-row justify-content-between align-items-center">
                    <div class="alt-fnt triple-root alt-fnt-extra-light">{{ schedule_weekday_string }}</div>
                    <div>
                        <button
                                class="material-symbols-outlined md-48 md-blue button icon-flip pointer"
                                hx-get="{% url 'schedule:personal-schedule' %}"
                                hx-vals='{"weekday": "{{ previous_day }}", "activity": "{{ activity_type }}"}'
                                hx-swap="multi:#user-activities,#activity-selection:outerHTML"
                                hx-push-url="true"
                        >next_plan</button>
                        <button
                                class="material-symbols-outlined md-48 md-blue button pointer"
                                hx-get="{% url 'schedule:personal-schedule' %}"
                                hx-vals='{"weekday": "{{ next_day}}", "activity": "{{ activity_type }}"}'
                                hx-swap="multi:#user-activities,#activity-selection:outerHTML"
                                hx-push-url="true"
                        >next_plan</button>
                    </div>
                </header>

                <section id="confirm-requests">

                </section>

                <section id="activity-list"
                         class="mt-4 d-flex flex-column ms-auto me-auto col-6"
                         hx-target="#user-content"
                         hx-select="#user-content"
                         hx-swap="outerHTML"
                         hx-boost="true"
                         hx-push-url="true"
                >
                    {% for activity in activities %}
                        <div class="transparent-board py-9 px-9 mt-7">
                            <div class="one-point-one-two-five-root medium">{{ activity }}</div>
                            <div class="row g-0 mt-6">

                                <div class="col subtext-shade light one-point-one-two-five-root">
                                    <div class="d-flex flex-row align-items-center">
                                        <span class="material-symbols-outlined md-36 md-grey me-2">linear_scale</span>
                                        <div>{{ activity.slug }}</div>
                                    </div>

                                    <div class="d-flex flex-row align-items-center mt-4">
                                        <span class="material-symbols-outlined md-36 md-grey me-2">explore</span>
                                        <div>{{ activity.get_location_display }}</div>
                                    </div>
                                </div>

                                <div class="col-6 alt-fnt alt-fnt-medium one-point-five-root">
                                    <div class="d-flex flex-row align-items-center justify-content-end">
                                        <div class="success px-4 py-4">{{ activity.start_time | date:"H:i" }}</div>
                                        <span class="material-symbols-outlined md-36 md-grey mx-2">trending_flat</span>
                                        <div class="error px-4 py-4">{{ activity.end_time | date:"H:i" }}</div>
                                    </div>
                                </div>

                                    {#  todo: set url here based on the type of schedule that was set #}
                                    <a href="{% url 'schedule:class-details' activity activity.id activity.slug %}"
                                   class="mt-8 medium zero-point-eight-seven-five-root
                                    {{ activity.schedule_type }}-syntax-highlight px-3 py-4 text-center"
                                    >View {{ activity.get_schedule_type_display }}</a>
                            </div>
                        </div>
                    {% endfor %}
                </section>
            </section>
        </main>
    </div>

{% endblock %}