conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("schedule/", include('staff_schedule.urls', namespace='schedule')),
    path('', include('user_configuration.urls', namespace='user_configuration')),
    path("my-tasks/", include('tasks.urls', namespace='my-tasks')),
    path('front-desk/', include('frontdesk.urls', namespace='front-desk')),
    path('executive/', include('executive.urls', namespace='executive')),
    path("payments/", include('payments.urls', namespace="payments")),
    path("trainer/", include('trainer.urls', namespace="trainer")),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, doument_root=settings.MEDIA_ROOT)

payments/urls.py
from django.urls import path

from payments import views

app_name = "payments"

urlpatterns = [
    path("my-earnings/", views.my_earnings, name="my-earnings"),
    path("payslip-breakdown/<int:payslip_identification>/", views.payslip_breakdown, name="payslip-breakdown"),
]

payments/models.py
from django.conf import settings
from django.db import models


# Create your models here.
from trainer.models import GroupClass


class PaySlip(models.Model):
    PAYSLIP_TYPES = [
        ("GNL", "General"),
        ("OOO", "One-on-One")
    ]
    paid = models.BooleanField(default=False)
    staff = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL)
    deductions = models.DecimalField(decimal_places=2, max_digits=10, default=0.00)
    total_clock_in_wage = models.DecimalField(decimal_places=2, max_digits=10, default=0.00)
    total_class_payment = models.DecimalField(decimal_places=2, max_digits=10, default=0.00)
    final_payment = models.DecimalField(decimal_places=2, max_digits=10, default=0.00)
    payment_confirmed = models.DateTimeField(blank=True, null=True)
    payslip_type = models.CharField(choices=PAYSLIP_TYPES, default="GNL", blank=False, max_length=3)


class GroupClassPayment(models.Model):
    payment_for_class = models.ForeignKey(GroupClass, on_delete=models.SET_NULL, null=True, blank=True)
    attendees = models.PositiveIntegerField(default=0, blank=True, null=True)
    attendance_logged = models.BooleanField(default=False)
    payment_request_created = models.DateTimeField(auto_now_add=True)
    time_of_payment = models.DateTimeField(null=True, blank=True)
    class_paid_for = models.BooleanField(default=False)
    total_payment = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
    sent_for_payment = models.BooleanField(default=False)
    payslip = models.ForeignKey(PaySlip, null=True, blank=True, on_delete=models.SET_NULL)

payments/views.py
from django.contrib.auth.decorators import user_passes_test, login_required
from django.core.paginator import Paginator
from django.shortcuts import render


# Create your views here.
from conf import constants
from conf.helper_functions import paginator_helper
from conf.url_tests import executive_test
from payments.models import PaySlip


@login_required()
def my_earnings(request):
    all_payslips = PaySlip.objects.filter(
        staff=request.user
    ).order_by("final_payment")
    total_payslips = all_payslips.count()
    total_payment = 0.00
    for payslip in all_payslips:
        total_payment += float(payslip.final_payment)

    page_object = paginator_helper(request, all_payslips, 10)
    context = {
        "total_payslips_count": total_payslips,
        "total_payment": total_payment,
        "first_payment": all_payslips.first(),
        "last_payment": all_payslips.last(),
        "page_object": page_object,
    }
    return render(request, "my-earnings.html", context)


@login_required()
def payslip_breakdown(request, payslip_identification):
    payslip = PaySlip.objects.get(
        id=int(payslip_identification),
        staff=request.user
    )
    is_trainer = constants.STAFF_MODEL.objects.filter(
        groups__name="Trainer",
        id=request.user.id
    ).exists()
    print(is_trainer)
    context = {
        "payslip": payslip,
        "is_trainer": is_trainer,
    }
    return render(request, "payslip-breakdown.html", context)

payments/templates/my-earnings.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}My Earnings{% endblock %}

{% block content %}
    <div id="user-content" class="mb-10">
        <main id="my-earnings">
            <section class="sub-page-divider pb-10 px-9">
                <header class="d-flex flex-column pe-7 mt-10">

                    <div class="d-flex flex-row align-items-center">
                        <h1 class="core-page-heading mb-0">My Earnings</h1>
                        <span class="material-symbols-outlined md-36 themed-icon ms-2">payment</span>
                    </div>
                    <div class="mt-2 core-content-subheading">
                        Your earnings page details all the payments that you have received from iSweat Fitness.
                    </div>

                    <div class="d-flex flex-row justify-content-between mt-10">
                        <div class="success-text">
                            <div>Total Payslips</div>
                            <div class="quadruple-root medium">{{ total_payslips_count }}</div>
                            <div class="subtext-shade zero-point-seven-five-root">
                                From {{ request.user.date_joined | date:"jS F o"}} to {% now "jS F o" %}
                            </div>
                        </div>

                        <div class="success-text">
                            <div>Total Payment</div>
                            <div class="quadruple-root medium">{{ total_payment | intcomma }} NGN</div>
                            <div class="subtext-shade zero-point-seven-five-root">
                                From {{ request.user.date_joined | date:"jS F o"}} to {% now "jS F o" %}
                        </div>
                        </div>
                    </div>

                </header>
            </section>

            <section class="px-9">
                <div class="mt-10 d-flex flex-row justify-content-between align-items-center">
                    <div class="double-root thin">Earnings History</div>
                </div>

                <section class="d-flex flex-column align-items-center" id="user-table">
                    <table class="table mt-9">
                        <thead class="subpage-table">
                            <tr>
                                <th scope="col" class="py-4 ps-10">ID</th>
                                <th scope="col" class="py-4 pe-14">Date Paid</th>
                                <th scope="col" class="py-4">Type</th>
                                <th scope="col" class="py-4">Total Paid</th>
                                <th scope="col" class="py-4"></th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for earning in page_object %}
                                <tr class="sub-table-data clock-in-table">
                                    <td class="py-5 table-non-core light ps-10">PSL-{{ earning.id }}</td>
                                    <td class="py-5 table-non-core light">{{ earning.payment_confirmed | date:"jS M Y" }}</td>
                                    <td class="py-5 table-core">{{ earning.get_payslip_type_display }}</td>
                                    <td class="py-5 table-core success-text semi-bold">{{ earning.final_payment | intcomma }} NGN</td>
                                    <td class="py-5 alternative-blue medium table-core" hx-boost="true" hx-select="#user-content"
                                        hx-target="#user-content" hx-swap="outerHTML">
                                        <a href="{% url 'payments:payslip-breakdown' earning.id %}">
                                        <span class="material-symbols-outlined md-36 ms-1">arrow_circle_right</span>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% include 'pagination.html' with select_id="#user-table" target_id="#user-table" %}
                </section>

            </section>
        </main>
    </div>
{% endblock %}

payments/templates/payslip-breakdown.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}Payslip Breakdown{% endblock %}

{% block content %}
    <main id="user-content" class="mb-10">
        <header id="payslip-breakdown"
                 class="header-content pb-10 px-9 sub-page-divider">
            <div class="d-flex flex-row pointer pt-10 pb-7 align-items-center"
                 hx-post="{% url 'payments:my-earnings' %}" hx-select="#user-content"
                 hx-target="#user-content" hx-swap="outerHTML" hx-push-url="true"
                 id="back-button">
                <span class="material-symbols-outlined md-24 md-grey">arrow_back</span>
                <span class="subtext-shade regular zero-point-eight-seven-five-root">Back to  My Earnings</span>
            </div>
            <div class="double-root thin">Breakdown of PSL-{{ payslip.id }}</div>
            <span class="mt-2 core-content-subheading">
                Here is how the final payment for PSL-{{ payslip.id }} was calculated.
            </span>

            <section class="d-flex flex-row flex-wrap mt-7 justify-content-between">
                <div class="d-flex flex-column transparent-board px-7 col-3 justify-content-between">
                    <span class="material-symbols-outlined md-36 md-grey mt-9">account_balance</span>
                    <div class="semi-bold one-point-one-two-five-root mt-4">Clock In Wage</div>
                    <div class="triple-root semi-bold my-2">{{ payslip.total_clock_in_wage | intcomma }}</div>
                    <div class="subtext-shade zero-point-eight-seven-five-root pb-7">Naira</div>
                </div>

                {% if is_trainer %}
                    <div class="d-flex flex-column transparent-board px-7 col-3 justify-content-between">
                        <span class="material-symbols-outlined md-36 md-grey mt-9">connect_without_contact</span>
                        <div class="semi-bold one-point-one-two-five-root mt-4">Classes</div>
                        <div class="triple-root semi-bold my-2">{{ payslip.total_class_payment | intcomma }}</div>
                        <div class="subtext-shade zero-point-eight-seven-five-root pb-7">Naira</div>
                    </div>

                    <div class="d-flex flex-column transparent-board px-7 col-3 justify-content-between">
                        <span class="material-symbols-outlined md-36 md-grey mt-9">home_pin</span>
                        <div class="semi-bold one-point-one-two-five-root mt-4">Home Training</div>
                        {# todo: home training #}
                        <div class="triple-root semi-bold my-2">{{ payslip.total_class_payment | intcomma }}</div>
                        <div class="subtext-shade zero-point-eight-seven-five-root pb-7">Naira</div>
                    </div>
                {% endif %}
            </section>

            <section class="d-flex flex-row flex-wrap mt-9 justify-content-between">
                {% if payslip.deductions > 0.00 %}
                    <div class="d-flex flex-column transparent-board px-7 col-3 justify-content-between failure-text">
                        <span class="material-symbols-outlined md-36 md-grey mt-9 md-red">do_not_disturb_on</span>
                        <div class="semi-bold one-point-one-two-five-root mt-7">Deductions</div>
                        <div class="triple-root semi-bold mt-2 mb-4">{{ payslip.deductions | intcomma }}</div>
                        <div class="zero-point-eight-seven-five-root mb-7">Naira</div>
                        <div class="mb-10 failure-mini-board d-flex flex-row px-6 py-7 align-items-center">
                            <span class="material-symbols-outlined md-36 md-red">offline_bolt</span>
                            <div class="d-flex flex-column ms-4 me-auto">
                                {# todo: name populate — change to ISMS name #}
                                <div class="medium zero-point-eight-seven-five-root text-white">ISMS | Clock Ins</div>
                                <div class="subtext-shade extra-light">ISMS.com</div>
                            </div>
                            <span class="material-symbols-outlined md-36 md-red">open_in_new</span>
                        </div>
                    </div>
                {% endif %}

                <div class="d-flex flex-column transparent-board px-7 col-3 justify-content-between success-text">
                    <span class="material-symbols-outlined md-36 md-grey mt-9 md-green">add_circle</span>
                    <div class="semi-bold one-point-one-two-five-root mt-7">Total Earned</div>
                    <div class="triple-root semi-bold mt-2 mb-4">{{ payslip.final_payment | intcomma }}</div>
                    <div class="zero-point-eight-seven-five-root mb-7">Naira</div>
                    <div class="mb-10 success-mini-board d-flex flex-row px-6 py-7 align-items-center">
                        <span class="material-symbols-outlined md-36 md-green">picture_as_pdf</span>
                        <div class="d-flex flex-column ms-4 me-auto">
                            {# todo: name populate — change to ISMS name #}
                            <div class="medium zero-point-eight-seven-five-root text-white">PSL-{{ payslip.id }}</div>
                            <div class="subtext-shade extra-light">{# todo: file and file size for payslip #}1MB</div>
                        </div>
                        <span class="material-symbols-outlined md-36 md-green">download</span>
                    </div>
                </div>

            {% if payslip.deductions > 0.00 %}
                {# false column placed here to ensure equal alignment #}
                <div class="col-3"></div>
            {% endif %}
            </section>
        </header>

        {# todo: full implementation in the future — not urgent #}
{#        {% if is_trainer %}#}
{#            <section id="breakdown-of-payment" class="px-9 mt-10">#}
{#                <div class="thin one-point-seven-five-root">Payslip Breakdown</div>#}
{#                <span class="mt-2 core-content-subheading mt-2">#}
{#                    Click on a board to see the breakdown for this payslip#}
{#                </span>#}
{##}
{#                <div class="d-flex flex-row mt-10 justify-content-between">#}
{#                    <div class="transparent-board px-7 col-3 pt-7">#}
{#                        <span class="material-symbols-outlined md-36 md-grey">connect_without_contact</span>#}
{#                        <div class="mb-6 mt-7 subtext-shade">View Breakdown For</div>#}
{#                        <div class="medium triple-root mb-6">Classes</div>#}
{#                        <span class="material-symbols-outlined md-48 md-blue mb-10">arrow_circle_right</span>#}
{#                    </div>#}
{##}
                    {# todo: home training #}
{#                    <div class="transparent-board px-7 col-3 pt-7">#}
{#                        <span class="material-symbols-outlined md-36 md-grey">connect_without_contact</span>#}
{#                        <div class="mb-6 mt-7 subtext-shade">View Breakdown For</div>#}
{#                        <div class="medium triple-root mb-6">Home</div>#}
{#                        <span class="material-symbols-outlined md-48 md-blue mb-10">arrow_circle_right</span>#}
{#                    </div>#}
{##}
{#                    <div class="col-3"></div>#}
{#                </div>#}
{##}
{#            </section>#}
{#        {% endif %}#}
    </main>
{% endblock %}